<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

- More details on accessing and modifying lists, arrays and dictionaries
- Better understanding of the differences and similarities between lists, NumPy arrays and dictionaries

# 1 Subsetting: Indexing and Slicing

- Subsetting means to ‘select’.
- Indexing refers to selecting one element.
- Slicing refers to selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
import numpy as np

In [4]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

# Pick one
# x = py_list  # OR
x = np_array

In [5]:
x[0]

'a1'

In [6]:
x[-1]

'j10'

In [7]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [9]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [10]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [11]:
x[:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [13]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [12]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [14]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[~(np_array > 3)]  # '~' means 'NOT'

array([1, 2, 3])

In [18]:
np_array[(np_array > 3) & (np_array < 8)]  # '&' means 'AND'

array([4, 5, 6, 7])

In [35]:
np_array[(np_array < 3) | (np_array > 8)]  # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [19]:
py_list_2d = [
    [1, "A"],
    [2, "B"],
    [3, "C"],
    [4, "D"],
    [5, "E"],
    [6, "F"],
    [7, "G"],
    [8, "H"],
    [9, "I"],
    [10, "J"],
]

np_array_2d = np.array(py_list_2d)

In [20]:
py_list_2d[3]
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [21]:
py_list_2d[3][0]
np_array_2d[3, 0]

'4'

In [22]:
py_list_2d[:3]
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [24]:
py_list_2d[:3][0]
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [25]:
py_list_2d[3:6][0]
np_array_2d[3:6, 0]
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [26]:
x = [1, 2] * 5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [27]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
x
x = [1]
x += [2]
x += [3]
x += [4]
x
x = [1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [28]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x = [1, 2, 3]
x.extend([4, 5, 6])
x
x = [1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [29]:
a = (1, 2, 3)  # Define tuple

In [30]:
print(a[0])  # Access data

1


In [32]:
# The following will NOT work
# a[0] = -1
# a[0] += [10]

## 1.6 Be VERY careful when copying

In [33]:
x = [1, 2, 3]
y = x  # DON'T do this!
z = x  # DON'T do this!

In [34]:
x = [1, 2, 3]
y = x.copy()
z = x.copy()